# Generated by Django 4.1.4 on 2023-06-20 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projectName', models.CharField(blank=True, default='', max_length=50)),
                ('projectImage', models.ImageField(default='', upload_to='images/')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('images', models.ManyToManyField(blank=True, related_name='projects', to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='projectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='project_likes', through='api.projectLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('All Creative Fields', 'All Creative Fields'), ('3D Art', '3D Art'), ('Architecture', 'Architecture'), ('Art Direction', 'Art Direction'), ('Branding', 'Branding'), ('Fashion', 'Fashion'), ('Graphic Design', 'Graphic Design'), ('Illustration', 'Illustration'), ('Industrial Design', 'Industrial Design'), ('Interaction Design', 'Interaction Design'), ('Motion Graphics', 'Motion Graphics'), ('Photography', 'Photography'), ('UI/UX', 'UI/UX'), ('Web Design', 'Web Design')], max_length=180, validators=[django.core.validators.MaxValueValidator(5)])),
                ('userImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to='api.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ManyToManyField(blank=True, related_name='profiles', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='api.project'),
        ),
    ]
